### ISSUE TITLE
Update Percona apt key

### ISSUE THREAD

**Issue by dlundgren** [HanXHX/ansible-mysql#13]
Percona has a new key used to sign packages: `9334A25F8507EFA5`

https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/

**Comment by HanXHX** [comment]
Done in percona branch: 9c0455afe2037c7693e29e4df14e530ffbc8f441
I'll merge it soon (waiting https://travis-ci.org/HanXHX/ansible-mysql/builds/174541455)

**Comment by HanXHX** [comment]
Done!
