### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Phill93** [HanXHX/ansible-mysql#23]
Hi,

the installation of this role fails at this point:

`TASK [HanXHX.mysql : TEMPLATE | Deploy extra configuration] *************************************************************************************************************
fatal: [xxx]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
	to retry, use: --limit @/Users/xxx/Projects/ansible-scaleway/playbook.retry`

I changed only this variables:
 - mysql_origin
- mysql_vendor
- mysql_root_password
- mysql_databases
- mysql_users

**Comment by Phill93** [comment]
I found out that this error occurs when using python 3.
If you replace iteritems with items, the error doesn't occur anymore.

PR is on the way

**Comment by HanXHX** [comment]
I'll have a look on your PR very soon. TY ;)
