### ISSUE TITLE
logrotate fails

### ISSUE THREAD

**Issue by Phill93** [HanXHX/ansible-mysql#25]
on my test machine logrotate fails to rotate the mysql logs with this message:

```
/etc/cron.daily/logrotate:
mysqladmin: flush failed; error: 'Unknown error'
error: error running shared postrotate script for '/var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/mariadb-slow.log /var/log/mysql/error.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

**Comment by Phill93** [comment]
i have discovered that this error occurs when a custom logging path is set

see [my.cnf](https://github.com/HanXHX/ansible-mysql/blob/master/templates/etc/mysql/my.cnf.j2#L15-L35)

**Comment by HanXHX** [comment]
Can you send me more infos please?

- OS?
- mysql vendor / version?

**Comment by Phill93** [comment]
OS: Debian 9 (stretch)
Vendor: MariaDB

**Comment by HanXHX** [comment]
Hi @Phill93,

I did some work in [newlog](https://github.com/HanXHX/ansible-mysql/tree/newlog) branch. I need more tests before merging in master.

However, your problem should not be logrotate related. I think your custom log path is not writeable. By default in Debian, all logs are writed in `/var/log/mysql`.

```
$ sudo stat /var/log/mysql/
  File: /var/log/mysql/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d	Inode: 391695      Links: 2
Access: (2750/drwxr-s---)  Uid: (  107/   mysql)   Gid: (    4/     adm)
Access: 2018-02-27 07:34:32.707702926 +0000
Modify: 2018-02-27 07:34:20.371753414 +0000
Change: 2018-02-27 07:34:20.371753414 +0000
 Birth: -
```

You can check with: `mysqladmin -u root -p flush-log`.
