### ISSUE TITLE
Debian buster start error

### ISSUE THREAD

**Issue by gbaudot** [HanXHX/ansible-mysql#36]
Hello.
Been trying for a while to test this role...
For the record, testing version 1.0 with Debian 9 (mariadb from upstream repo), I did not manage to enable a galera cluster, and got a valid master/slave setup after a few minor changes in code (like replacing missing mariadb command with mysql).
Then, trying new version 1.1.0 with Debian10 (mariadb from debian repo), it looks like galera almost worked "out of the box", with a non blocking error: service starts and is considered active, but ExecStartPost command /etc/mysql/debian-start fails due to invalid credentials (apparently due to missing root password in /etc/mysql/debian.cnf).
Now I wonder about the proper solution: should this debian-start command be avoided/removed from unit, or does role lack properly setting up this /etc/mysql/debian.cnf file (filling root password) in order to get command running, or even smth else?.. And since I am unsure about how to do it right, I would be glad if you could give me a hand here (either telling me what would be the right fix, or implementing it yourself if you feel like).
Hope this description of the issue is enough, as I am going to be on a quite long holiday and will hardly be online in the mean time...
Anyway, thanks for your nice work on this role.

**Comment by HanXHX** [comment]
Hi! I will have a look in few days. Can you send more information? Like ansible variables used, hosting provider (aws?), error messages...

**Comment by gbaudot** [comment]
Hello. And thanks for the fast answer. Anyway, being in holiday during one
month ans far away from computers, i would be glad if we could discuss it
later. Cheers.

**Comment by gbaudot** [comment]
Hello.
Coming back from holiday, I come for an update...
After a last try before leaving, I managed to get a working 3 VMs cluster, then I guess there was a mistake in my setup and you may as well consider subject is closed.
Sorry for the inconvenience, regards.

PS: considering your last build failure, you might consider using mysql command instead of mariadb (which is just a link to mysql when present and seems missing on travis platform)

GB

**Comment by HanXHX** [comment]
Hi @gbaudot ,

I close this issue. I did lot of work on this project. Feel free to open a new issue if needed.

Cheers,

EM
