### ISSUE TITLE
proper cluster restart failure when changing configuration

### ISSUE THREAD

**Issue by gbaudot** [HanXHX/ansible-mysql#39]
Hello.
Having mysql data on its own ext4 FS in production, I had to add "ignore_db_dirs = lost+found" in my extra config.
Then testing the change on VMs, I could notice role fails to restart Galera cluster properly with this change. Looking at code, I also naively tested adding "mariadb_galera_resetup = true" option, but this failed as well (just not at same step). In both cases, I could easily recover cluster anyway.
So, did I do something wrong, missing the obvious ?.. or did I hit a corner case (where temporary service discontinuity is required) ?

Notes:
- to avoid a failure, I simply opted for manual operations on my production servers: stop cluster/fix extra config file/start cluster (and once option set in ansible configuration, role could be replayed without any error then, since required change was already applied).
- indeed, I could have noticed and set  the extra config option before !

Anyway, many thanks for this great role.

Regards,
GB

**Comment by maximumG** [comment]
I had the same issue as yours @gbaudot . The main problem is that all members of the cluster are restarted at the same time by Ansible.

https://github.com/HanXHX/ansible-mysql/blob/ab76aa019dc66e0e77ba3941e684a9ac45e52d34/tasks/main.yml#L28

I solved the issue by adding `throttle: 1` to the task `SERVICE | Restart now (prevent bugs)`. By doing this way all MariaDB servers are rebooted one after another correctly, without disrupting the galera primary component.

I will submit a push request for this correction

**Comment by gbaudot** [comment]
Hello. Nice shot. I should have thought about it on my own... (in fact, I happened to forget about this issue since I did not have to change config again). In addition, this change may require ansible min version bump...

Regards,
GB

**Comment by HanXHX** [comment]
Hi,

You can use `serial` keyword on you playbook. I think it's the better way to manage clusters.
But `throttle` can be another solution.

Cheers,

EM

**Comment by maximumG** [comment]
> You can use `serial` keyword on you playbook. I think it's the better way to manage clusters.
> But `throttle` can be another solution.

I first thought about using `serial` in my own playbook in order not to modify the role. But from what I learned, the `strategy: serial` will behave in serial for **all** tasks in the role. This really slow down the whole deployment :disappointed_relieved:  (mix of a 3 nodes galera cluster + 2 nodes with MariaDB master-slave replication).

`Throttle` on his side will only slow down specific task in the role himself, here it will only slow down the reboot tasks.

**Comment by HanXHX** [comment]
Yep I know. I just give you a short term solution :wink:.

Can you send me a PR with `serial` please? I can merge it quickly.

**Comment by maximumG** [comment]
Pull request #40 is ready for approval on your side
