### ISSUE TITLE
Galera cluster customization

### ISSUE THREAD

**Issue by maximumG** [HanXHX/ansible-mysql#42]
I worked on some enhancements regarding galera cluster configuration / async replication for some internal deployment at work. Would you be interested in these changes if I propose a pull request ?

* Add possibility to use *mariabackup/xtrabackup* as SST method with automatic local user creation (https://mariadb.com/kb/en/mariabackup-sst-method/)
* Customize some *wsrep* variables from within the role's variable
* For async replication, add a task to create the user/password, instead of relying on _mariadb_users_ table.

**Comment by HanXHX** [comment]
Hi,

You already can tune `mariadb_wsrep_stt_method` variable.

About //wsrep_// variables, feel free to create a new PR. Just keep in mind, to set defaults values in [defaults/main.yml](https://github.com/HanXHX/ansible-mysql/blob/master/defaults/main.yml)

About async replication, I'm not sure it's a good way to tune users in this role. You can have many usages (can be managed with vars):
- all writes in master + with mysql.user replicated just tune `mariadb_users` in your //host_vars//
- different users on user/master
...

Cheers,

EM
