### ISSUE TITLE
Use no_log in MYSQL_USER | Manages users...

### ISSUE THREAD

**Issue by gh-PonyM** [HanXHX/ansible-mysql#43]
Thanks for your ansible role that you provide to the community. In order not to leak passwords through the logs, the `no_log: True` option can be edded to the mentioned task. What do you think?

**Comment by HanXHX** [comment]
It can be a good idea. But I need to find the good way with security (hiding password) and easy debugging (no_log hides everything).

I'm working to port this role on Debian 11, i'll have a look next.

**Comment by gh-PonyM** [comment]
It's a good point with the debugging. I had the same problem. I think you test your role with galaxy. I can't tell you, if you can set a variable indicating testing. I like to test my playbooks in vagrant (here as example: https://gist.github.com/DadaDaMotha/5e2b3fee5fe16ad71af75fdebf8d1ae8) and I set e.g. the variable `no_log: "{{ not running_in_vagrant | default(True, true) }}"`.

**Comment by HanXHX** [comment]
Done on 860b212
