### ISSUE TITLE
APT pinning (prevent upgrades from Debian) issue

### ISSUE THREAD

**Issue by dw-guillaumed** [HanXHX/ansible-mysql#8]
Hello

When i use your nice role on debian wheezy, i have some trouble with the path for the APT pinning, indeed when i changed the path with a relative path like this `src=etc/apt/preferences.d/95-percona.j2` it's working well but not with `src=../../../templates/etc/apt/preferences.d/95-percona.j2`

```
TASK [HanXHX.mysql : TEMPLATE | Deploy APT pinning (prevent upgrades from Debian)] ***
fatal: [db-01.xxx.com]: FAILED! => {"changed": false, "failed": true, "msg": "IOError: [Errno 2] No such file or directory: u'/home/xxxx/templates/etc/apt/preferences.d/95-percona.j2'"}
``

Thanks
```

**Comment by HanXHX** [comment]
Hi @dw-guillaumed,

Can you paste your vars please? and your ansible version?

I'll see that.

EM

**Comment by HanXHX** [comment]
Oh i see the problem. I fix this right now.

**Comment by dw-guillaumed** [comment]
perfect, thanks ;-)
