### ISSUE TITLE
Percona install, template location

### ISSUE THREAD

**Issue by unitiva-sistemi** [HanXHX/ansible-mysql#9]
When I execute the role to install Percona, I receive following error message:

fatal: [_server_name_] => input file not found at /_path_to_ansible_/roles/HanXHX.mysql/tasks/install/templates/etc/apt/preferences.d/95-percona.j2 or /_path_to_ansible_/playbooks/etc/apt/preferences.d/95-percona.j2

but the templates folder is at this path: /_path_to_ansible_/roles/HanXHX.mysql/templates/

**Comment by HanXHX** [comment]
Hi @abstract-srl,

Can you give me:
- your ansible version
- vars

Thanks,

Emilien

**Comment by unitiva-sistemi** [comment]
- ansible version: 1.9.4
- vars:
  mysql_origin: 'upstream'
  mysql_vendor: 'percona'
  mysql_use_percona_repository: false

**Comment by HanXHX** [comment]
OK, this problem has been fixed many days ago: see #8 

You can upgrade role: `ansible-galaxy -f HanXHX.mysql`

**Comment by unitiva-sistemi** [comment]
I already used the fixed version, it seems that the relative path:

`template: src=etc/apt/preferences.d/95-percona.j2 dest=/etc/apt/preferences.d/95-percona`

doesn't start from the root folder of the role, but from the install/ folder.

**Comment by HanXHX** [comment]
OK I just tested with Vagrant. My role is not compatible yet with Ansible 1.x. You must use Ansible 2. I changed it in d232b7b.
